console.log('-----------create-------------')
let div = dom.create('<div>hi</div>')
let div1 = dom.create('<div>bye</div>')
let div2 = dom.create('<div>pop</div>')
let div3 = dom.create('<div>wrapper</div>')
console.log(div)
dom.after(test, div1)
dom.before(test,div)
dom.append(test, div2)
dom.wrap(test, div3)

console.log('-----------delete-------------')
dom.remove(div1)
console.log(dom.empty(test))

console.log('-----------update-------------')
dom.attr(test, 'title', 'test_div')
console.log(dom.attr(test, 'title'))
dom.text(test, 'new_test')
console.log(dom.text(test))
dom.html(test, '<div>new_test</div>')
console.log(dom.html(test))
dom.style(test, 'color', 'red')
console.log(dom.style(test, 'color'))
dom.style(test, {border: '1px solid yellow', color: 'blue'})
dom.class.add(test, 'red')
dom.class.add(test, 'blue')
dom.class.remove(test, 'blue')
console.log(dom.class.has(test, 'blue'))
const fn = () => {console.log('click on' + this)}
dom.on(test, 'click', fn)
dom.off(test, 'click', fn)

console.log('------------read--------------')
const testDiv = dom.find('#test')[0]
console.log(testDiv)
console.log(dom.find('div', testDiv)[0])
console.log(dom.find('#test>div'))
console.log('---parent:---')
console.log(dom.parent(test))
console.log('---children:---')
console.log(dom.children(test))
console.log('---siblings:---')
dom.after(test, div1)
dom.after(test, div2)
console.log(dom.siblings(test))
console.log('---next:---')
console.log(dom.next(test))
console.log('---prev:---')
dom.before(test, div)
console.log(dom.previous(test))
const wrapperDiv = dom.find('div')[0]
dom.each(dom.children(wrapperDiv), node => dom.style(node, 'color', 'cyan'))
console.log('---index:---')
console.log(dom.index(test))